version: '3.0'

services:
  # PHP
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - vendorcache:/var/www/html/vendor
    ports:
      - 8000:8000
    command: sh ./init.sh

  # MySQL
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqldata:/var/lib/mysql

  # Phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  # Mailhog
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

# Volumes
volumes:
  mysqldata:
    driver: local
  vendorcache:
    driver: local
